In [2]:
import tensorflow as tf

# Sigmoid函数
x = tf.linspace(-6., 6., 10) # 构造 -6　～　６的输入向量
tf.nn.sigmoid(x) # 将输入压缩到（0，1）区间

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00247264, 0.00931591, 0.03444517, 0.11920291, 0.33924365,
       0.6607564 , 0.8807971 , 0.96555483, 0.99068403, 0.99752736],
      dtype=float32)>

In [3]:
# ReLU函数
tf.nn.relu(x) # 单边抑制，保留正数，去除负数

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.      , 0.      , 0.      , 0.      , 0.      , 0.666667,
       2.      , 3.333334, 4.666667, 6.      ], dtype=float32)>

In [4]:
# LeakyReLU函数
tf.nn.leaky_relu(x, alpha=0.1) # 输入x，若x为正数，则输出x；若x为负数，则输出alpha * x

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.6       , -0.46666667, -0.33333334, -0.2       , -0.06666666,
        0.666667  ,  2.        ,  3.333334  ,  4.666667  ,  6.        ],
      dtype=float32)>

In [5]:
# Tanh函数
tf.nn.tanh(x) # 将输入压缩到（-1，1）区间

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.99998784, -0.99982315, -0.9974579 , -0.9640276 , -0.58278286,
        0.58278316,  0.9640276 ,  0.99745804,  0.99982315,  0.99998784],
      dtype=float32)>

In [6]:
# Softmax函数
z = tf.constant([2., 1., 0.1])
tf.nn.softmax(z) # 将输出转化为概率，加起来和为1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6590012 , 0.24243298, 0.09856589], dtype=float32)>