In [1]:
import tensorflow as tf

In [2]:
z = tf.random.normal([2,10]) # 构造输出层的输出
y_onehot = tf.constant([1,3]) # 构造真实值
y_onehot = tf.one_hot(y_onehot, depth=10) # one-hot 编码

# 输出层未使用Softmax函数，故from_logits设置为True
# 这样categorical_crossentropy函数在计算损失函数前，会先内部调用Softmax函数
loss = tf.keras.losses.categorical_crossentropy(y_onehot, z, from_logits=True)
loss = tf.reduce_mean(loss) # 计算平均交叉熵
loss

<tf.Tensor: shape=(), dtype=float32, numpy=3.1180868>

In [3]:
# 创建Softmax与交叉熵计算类，输出层的输出z未使用softmax
criteon = tf.keras.losses.CategoricalCrossentropy(from_logits=True)
loss = criteon(y_onehot, z) # 计算损失
loss

<tf.Tensor: shape=(), dtype=float32, numpy=3.1180868>

In [8]:
# 均方差误差函数（MSE）
o = tf.random.normal([2, 10]) # 构造网络输出
y_onehot = tf.constant([1, 3]) # 构造真实值
y_onehot = tf.one_hot(y_onehot, depth=10)
loss = tf.keras.losses.MSE(y_onehot, o) # 计算均方差
loss = tf.reduce_mean(loss) # 计算batch均方差
loss

<tf.Tensor: shape=(), dtype=float32, numpy=1.2893137>

In [9]:
# 通过层方式实现均方差误差函数
criteon = tf.keras.losses.MeanSquaredError() # 创建MSE类
loss = criteon(y_onehot, o) # 计算batch均方差
loss

<tf.Tensor: shape=(), dtype=float32, numpy=1.2893137>